# [문제1]
아래 출력 결과를 참고하여 DataFrame을 생성하여 df라는 이름으로 저장하는 코드를 작성하시오.

[출력]

        food			price		rating
        
0	KFC			1000		4.5

1	McDonald		2000		3.9

2	SchoolFood		2500		4.2

In [3]:
import pandas as pd

data = {
    "food" : ["KFC", "McDonald", "SchoolFood"],
    "price" : [1000, 2000, 2500],
    "rating" : [4.5, 3.9, 4.2]
}
col = ["food", "price", "rating"]
df = pd.DataFrame(data, columns=col)
df

         food  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2

# [문제2]
문제 1에서 food 컬럼과 rating 컬럼만 선택하여 출력하는 코드를 작성하시오.

[출력]

	food			rating
    
0	KFC			4.5

1	McDonald		3.9

2	SchoolFood		4.2

In [6]:
df[["food", "rating"]]

         food  rating
0         KFC     4.5
1    McDonald     3.9
2  SchoolFood     4.2

# [문제3]
문제 1에서 food 컬럼명을 place로 컬럼명을 변경하는 코드를 작성하시오.

[출력]

	place			price		rating
    
0	KFC			1000		4.5

1	McDonald		2000		3.9

2	SchoolFood		2500		4.2

In [10]:
df = df.rename({"food" : "place"}, axis=1)
df

        place  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2